import { Bank, Product, RateDisplay } from '@/types';

export const mockBanks: Bank[] = [
  {
    id: '1',
    name: 'Sampath Bank',
    shortCode: 'SAMP',
    websiteUrl: 'https://www.sampath.lk',
    bankType: 'private_domestic',
    fitchRating: 'AA-(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 15,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '2',
    name: 'Commercial Bank',
    shortCode: 'COMB',
    websiteUrl: 'https://www.combank.lk',
    bankType: 'private_domestic',
    fitchRating: 'AA-(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 15,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '3',
    name: 'Hatton National Bank',
    shortCode: 'HNB',
    websiteUrl: 'https://www.hnb.net',
    bankType: 'private_domestic',
    fitchRating: 'AA-(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 15,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '4',
    name: 'Bank of Ceylon',
    shortCode: 'BOC',
    websiteUrl: 'https://www.boc.lk',
    bankType: 'state',
    fitchRating: 'AA(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 10,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '5',
    name: "People's Bank",
    shortCode: 'PB',
    websiteUrl: 'https://www.peoplesbank.lk',
    bankType: 'state',
    fitchRating: 'AA(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 10,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '6',
    name: 'Standard Chartered',
    shortCode: 'SCB',
    websiteUrl: 'https://www.sc.com/lk',
    bankType: 'foreign',
    fitchRating: 'AA+(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 8,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '7',
    name: 'DFCC Bank',
    shortCode: 'DFCC',
    websiteUrl: 'https://www.dfcc.lk',
    bankType: 'private_domestic',
    fitchRating: 'A+(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 25,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '8',
    name: 'Nations Trust Bank',
    shortCode: 'NTB',
    websiteUrl: 'https://www.nationstrust.com',
    bankType: 'private_domestic',
    fitchRating: 'A(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 30,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '9',
    name: 'Seylan Bank',
    shortCode: 'SEYB',
    websiteUrl: 'https://www.seylan.lk',
    bankType: 'private_domestic',
    fitchRating: 'A-(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 35,
    riskTier: 'moderate',
    isActive: true,
  },
  {
    id: '10',
    name: 'Pan Asia Bank',
    shortCode: 'PABC',
    websiteUrl: 'https://www.pabc.lk',
    bankType: 'private_domestic',
    fitchRating: 'BBB-(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 55,
    riskTier: 'moderate',
    isActive: true,
  },
  {
    id: '11',
    name: 'Union Bank',
    shortCode: 'UB',
    websiteUrl: 'https://www.unionbank.lk',
    bankType: 'private_domestic',
    fitchRating: 'BBB+(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 45,
    riskTier: 'moderate',
    isActive: true,
  },
  {
    id: '12',
    name: 'HSBC',
    shortCode: 'HSBC',
    websiteUrl: 'https://www.hsbc.lk',
    bankType: 'foreign',
    fitchRating: 'AA(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 12,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '13',
    name: 'Amana Bank',
    shortCode: 'AMANA',
    websiteUrl: 'https://www.amanabank.lk',
    bankType: 'private_domestic',
    fitchRating: 'A(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 30,
    riskTier: 'low',
    isActive: true,
  },
  {
    id: '14',
    name: 'Cargills Bank',
    shortCode: 'CARG',
    websiteUrl: 'https://www.cargillsbank.lk',
    bankType: 'private_domestic',
    fitchRating: 'BBB(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 50,
    riskTier: 'moderate',
    isActive: true,
  },
  {
    id: '15',
    name: 'National Savings Bank',
    shortCode: 'NSB',
    websiteUrl: 'https://www.nsb.lk',
    bankType: 'state',
    fitchRating: 'AA-(lka)',
    cbslCategory: 'Licensed Commercial Bank',
    riskScore: 12,
    riskTier: 'low',
    isActive: true,
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    bankId: '1',
    category: 'fixed_deposit',
    name: 'Sampath Fixed Deposit',
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 13.5,
    interestRateSenior: 14.0,
    interestCalculationMethod: 'Monthly',
    interestPaymentFrequency: 'Monthly',
    minDepositLkr: 10000,
    fdTenureMinMonths: 1,
    fdTenureMaxMonths: 60,
    fdAllowedTenures: [1, 3, 6, 12, 24, 36, 48, 60],
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'visa',
      chequeBook: false,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
      autoRenewal: true,
      loanFacility: true,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '2',
    bankId: '2',
    category: 'fixed_deposit',
    name: 'Commercial Bank Fixed Deposit',
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 13.25,
    interestRateSenior: 13.75,
    interestCalculationMethod: 'Monthly',
    interestPaymentFrequency: 'Monthly',
    minDepositLkr: 10000,
    fdTenureMinMonths: 1,
    fdTenureMaxMonths: 60,
    fdAllowedTenures: [1, 3, 6, 12, 24, 36, 48, 60],
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'visa',
      chequeBook: false,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
      autoRenewal: true,
      loanFacility: true,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '3',
    bankId: '3',
    category: 'fixed_deposit',
    name: 'HNB Fixed Deposit',
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 13.0,
    interestRateSenior: 13.5,
    interestCalculationMethod: 'Monthly',
    interestPaymentFrequency: 'Monthly',
    minDepositLkr: 10000,
    fdTenureMinMonths: 1,
    fdTenureMaxMonths: 60,
    fdAllowedTenures: [1, 3, 6, 12, 24, 36, 48, 60],
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'visa',
      chequeBook: false,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
      autoRenewal: true,
      loanFacility: true,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '4',
    bankId: '7',
    category: 'fixed_deposit',
    name: 'DFCC Fixed Deposit',
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 14.0,
    interestRateSenior: 14.5,
    interestCalculationMethod: 'Monthly',
    interestPaymentFrequency: 'Monthly',
    minDepositLkr: 10000,
    fdTenureMinMonths: 1,
    fdTenureMaxMonths: 60,
    fdAllowedTenures: [1, 3, 6, 12, 24, 36, 48, 60],
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'mastercard',
      chequeBook: false,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
      autoRenewal: true,
      loanFacility: true,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '5',
    bankId: '5',
    category: 'fixed_deposit',
    name: "People's Bank Fixed Deposit",
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 12.75,
    interestRateSenior: 13.25,
    interestCalculationMethod: 'Monthly',
    interestPaymentFrequency: 'Monthly',
    minDepositLkr: 5000,
    fdTenureMinMonths: 1,
    fdTenureMaxMonths: 60,
    fdAllowedTenures: [1, 3, 6, 12, 24, 36, 48, 60],
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'local',
      chequeBook: false,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
      autoRenewal: true,
      loanFacility: true,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '6',
    bankId: '1',
    category: 'savings',
    name: 'Sampath Savings Account',
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 7.5,
    interestCalculationMethod: 'Daily Balance',
    interestPaymentFrequency: 'Monthly',
    minBalanceLkr: 2500,
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'visa',
      chequeBook: true,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '7',
    bankId: '2',
    category: 'savings',
    name: 'Commercial Bank Savings Account',
    targetAudience: ['residents', 'expats', 'seniors'],
    interestRateRegular: 7.25,
    interestCalculationMethod: 'Daily Balance',
    interestPaymentFrequency: 'Monthly',
    minBalanceLkr: 2500,
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'visa',
      chequeBook: true,
      standingOrders: true,
      smsAlerts: true,
      foreignCurrency: false,
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
  {
    id: '8',
    bankId: '1',
    category: 'foreign_currency',
    name: 'Sampath FC Account',
    targetAudience: ['expats', 'residents'],
    interestRateRegular: 3.5,
    interestCalculationMethod: 'Monthly',
    interestPaymentFrequency: 'Monthly',
    minBalanceUsd: 500,
    features: {
      onlineBanking: true,
      mobileApp: true,
      atmCard: 'visa',
      chequeBook: false,
      standingOrders: false,
      smsAlerts: true,
      foreignCurrency: true,
      currencies: ['USD', 'GBP', 'EUR', 'AUD'],
    },
    isActive: true,
    lastVerifiedDate: '2024-04-15',
  },
];

export const getBankById = (id: string): Bank | undefined => {
  return mockBanks.find((bank) => bank.id === id);
};

export const getProductsByBankId = (bankId: string): Product[] => {
  return mockProducts.filter((product) => product.bankId === bankId);
};

export const getProductsWithBanks = (): (Product & { bank: Bank })[] => {
  return mockProducts
    .map((product) => {
      const bank = getBankById(product.bankId);
      if (!bank) return null;
      return { ...product, bank };
    })
    .filter((item): item is Product & { bank: Bank } => item !== null);
};

export const getBestRates = (category: string = 'fixed_deposit', limit: number = 4): RateDisplay[] => {
  const productsWithBanks = getProductsWithBanks()
    .filter((p) => p.category === category)
    .sort((a, b) => b.interestRateRegular - a.interestRateRegular)
    .slice(0, limit);

  return productsWithBanks.map((p) => ({
    product: p,
    bank: p.bank,
    effectiveRate: p.interestRateRegular,
    tenureLabel: '12 Months',
  }));
};

export const getBanksByType = (type: string): Bank[] => {
  if (type === 'all') return mockBanks;
  return mockBanks.filter((bank) => bank.bankType === type);
};
